server:
  port: 8090
spring:
  application:
    name: loans
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://localhost:5433/loansdb
    driverClassName: org.postgresql.Driver
    username: admin
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8071/

management:
  endpoints:
    web:
      exposure:
        include: "*"
