spring:
    config:
        activate:
            on-profile: "qa"
build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@example.com"
  onCallSupport:
    - "(555) 555-****"
    - "(555) 523-****"