services:
  accountsdb:
    image: postgres
    container_name: accountsdb
    ports: 
     - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=accountsdb
    extends:
      file: common-config.yaml
      service: network-deploy-service

  loansdb:
    image: postgres
    container_name: loansdb
    ports: 
     - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=loansdb
    extends:
      file: common-config.yaml
      service: network-deploy-service

  cardsdb:
    image: postgres
    container_name: cardsdb
    ports: 
     - 5434:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cardsdb
    extends:
      file: common-config.yaml
      service: network-deploy-service

  configserver:
    image: "koushikreddy/configserver:s7"
    container_name: configserver-ms
    ports:
      - "8071:8071"

    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-base-config

  accounts:
    image: "koushikreddy/accounts:s7"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: jdbc:postgresql://accountsdb:5432/accountsdb
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

  loans:
    image: "koushikreddy/loans:s7"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: jdbc:postgresql://loansdb:5432/loansdb
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

  cards:
    image: "koushikreddy/cards:s7"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: jdbc:postgresql://cardsdb:5432/cardsdb
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

networks:
  koushikreddy:
    driver: "bridge"